import React from 'react';

import Arrownext from '../../../asset/svg/arrow-next.svg';
import Arrowprev from '../../../asset/svg/arrow-prev.svg';
import Clubs from '../../../asset/svg/clubs.svg';
import Contrast from '../../../asset/svg/contrast.svg';
import Current from '../../../asset/svg/current.svg';
import Diamonds from '../../../asset/svg/diamonds.svg';
import Direction from '../../../asset/svg/direction.svg';
import DownDirection from '../../../asset/svg/downDirection.svg';
import Heart from '../../../asset/svg/heart.svg';
import Help from '../../../asset/svg/help.svg';
import List from '../../../asset/svg/list.svg';
import Map from '../../../asset/svg/map.svg';
import Navigation from '../../../asset/svg/navigation.svg';
import Numbering from '../../../asset/svg/numbering.svg';
import Railway from '../../../asset/svg/railway.svg';
import Spades from '../../../asset/svg/spades.svg';
import Swipe from '../../../asset/svg/swipe.svg';
import Tap from '../../../asset/svg/tap.svg';
import ToLink from '../../../asset/svg/toLink.svg';

const ArrownextIcon = () => <Arrownext />;
const ArrowprevIcon = () => <Arrowprev />;
const ClubsIcon = () => <Clubs />;
const ContrastIcon = () => <Contrast />;
const CurrentIcon = () => <Current />;
const DiamondsIcon = () => <Diamonds />;
const DirectionIcon = () => <Direction />;
const DownDirectionIcon = () => <DownDirection />;
const HeartIcon = () => <Heart />;
const HelpIcon = () => <Help />;
const ListIcon = () => <List />;
const MapIcon = () => <Map />;
const NavigationIcon = () => <Navigation />;
const NumberingIcon = () => <Numbering />;
const RailwayIcon = () => <Railway />;
const SpadesIcon = () => <Spades />;
const SwipeIcon = () => <Swipe />;
const TapIcon = () => <Tap />;
const ToLinkIcon = () => <ToLink />;

export { ArrownextIcon, ArrowprevIcon, ClubsIcon, ContrastIcon, CurrentIcon, DiamondsIcon, DirectionIcon, DownDirectionIcon, HeartIcon, HelpIcon, ListIcon, MapIcon, NavigationIcon, NumberingIcon, RailwayIcon, SpadesIcon, SwipeIcon, TapIcon, ToLinkIcon };
