import React from 'react';

import Arrownext from '../../../asset/svg/arrow-next.svg';
import Arrowprev from '../../../asset/svg/arrow-prev.svg';
import Clubs from '../../../asset/svg/clubs.svg';
import Contrast from '../../../asset/svg/contrast.svg';
import Current from '../../../asset/svg/current.svg';
import Diamonds from '../../../asset/svg/diamonds.svg';
import Direction from '../../../asset/svg/direction.svg';
import DownDirection from '../../../asset/svg/downDirection.svg';
import Heart from '../../../asset/svg/heart.svg';
import Help from '../../../asset/svg/help.svg';
import List from '../../../asset/svg/list.svg';
import Map from '../../../asset/svg/map.svg';
import Navigation from '../../../asset/svg/navigation.svg';
import Numbering from '../../../asset/svg/numbering.svg';
import Railway from '../../../asset/svg/railway.svg';
import Spades from '../../../asset/svg/spades.svg';
import Swipe from '../../../asset/svg/swipe.svg';
import Tap from '../../../asset/svg/tap.svg';
import ToLink from '../../../asset/svg/toLink.svg';

export const ArrownextIcon = () => <Arrownext />;
export const ArrowprevIcon = () => <Arrowprev />;
export const ClubsIcon = () => <Clubs />;
export const ContrastIcon = () => <Contrast />;
export const CurrentIcon = () => <Current />;
export const DiamondsIcon = () => <Diamonds />;
export const DirectionIcon = () => <Direction />;
export const DownDirectionIcon = () => <DownDirection />;
export const HeartIcon = () => <Heart />;
export const HelpIcon = () => <Help />;
export const ListIcon = () => <List />;
export const MapIcon = () => <Map />;
export const NavigationIcon = () => <Navigation />;
export const NumberingIcon = () => <Numbering />;
export const RailwayIcon = () => <Railway />;
export const SpadesIcon = () => <Spades />;
export const SwipeIcon = () => <Swipe />;
export const TapIcon = () => <Tap />;
export const ToLinkIcon = () => <ToLink />;
