import React from 'react';

import IconArrownext from '../../../asset/svg/arrow-next.svg';
import IconArrowprev from '../../../asset/svg/arrow-prev.svg';
import IconClubs from '../../../asset/svg/clubs.svg';
import IconContrast from '../../../asset/svg/contrast.svg';
import IconCurrent from '../../../asset/svg/current.svg';
import IconDiamonds from '../../../asset/svg/diamonds.svg';
import IconDirection from '../../../asset/svg/direction.svg';
import IconHeart from '../../../asset/svg/heart.svg';
import IconHelp from '../../../asset/svg/help.svg';
import IconList from '../../../asset/svg/list.svg';
import IconMap from '../../../asset/svg/map.svg';
import IconNavigation from '../../../asset/svg/navigation.svg';
import IconNumbering from '../../../asset/svg/numbering.svg';
import IconRailway from '../../../asset/svg/railway.svg';
import IconSpades from '../../../asset/svg/spades.svg';
import IconSwipe from '../../../asset/svg/swipe.svg';
import IconTap from '../../../asset/svg/tap.svg';
import IconToLink from '../../../asset/svg/toLink.svg';

const Arrownext = () => <IconArrownext />;
const Arrowprev = () => <IconArrowprev />;
const Clubs = () => <IconClubs />;
const Contrast = () => <IconContrast />;
const Current = () => <IconCurrent />;
const Diamonds = () => <IconDiamonds />;
const Direction = () => <IconDirection />;
const Heart = () => <IconHeart />;
const Help = () => <IconHelp />;
const List = () => <IconList />;
const Map = () => <IconMap />;
const Navigation = () => <IconNavigation />;
const Numbering = () => <IconNumbering />;
const Railway = () => <IconRailway />;
const Spades = () => <IconSpades />;
const Swipe = () => <IconSwipe />;
const Tap = () => <IconTap />;
const ToLink = () => <IconToLink />;

export { Arrownext, Arrowprev, Clubs, Contrast, Current, Diamonds, Direction, Heart, Help, List, Map, Navigation, Numbering, Railway, Spades, Swipe, Tap, ToLink };
